### ISSUE TITLE
Crear vista de Nosotros - frontend

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#11]
- Reutilizar el header y footer
- Se tiene que respetar la paleta de colores que manejamos hasta el momento
- Contar con texto referente a nosotros como empresa
- Adaptarlo a las demás vistas

**Comment by DiegoCuadros** [comment]
Trabajando aca https://github.com/AnderMendoza/Ecommerce-Template/issues/106

**Comment by AnderMendoza** [comment]
Faltaría la integración de los archivos trabajados en el repositorio antiguo al modelo MVC.

**Comment by DiegoCuadros** [comment]
Realizado Importacion al modelo MVC

**Comment by AnderMendoza** [comment]
Se ha conectado con cada una de las vistas de manera exitosa, buen trabajo 🤜🤛
