### ISSUE TITLE
Crear tablas no relacionales - backend

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#14]
- Utilizar MongoDB para la creación de la base de datos
- Armar un gráfico de tablas, donde se muestre la distribución y el orden de la base de datos.
Algunos ejemplos:

![Image](https://user-images.githubusercontent.com/80181518/199149725-2f332a19-52a1-4a91-8e96-2f466d85db9d.png)

**Comment by AnderMendoza** [comment]
Para la creación de nuestros JSON encontré esta [página web](https://[generatedata.com](https://generatedata.com/) que hará más fácil la creación de nuestros JSON

**Comment by Jankarurosu** [comment]
Se termino de agregar los 15 datos a la tabla de blogs en la base de datos Stose:



![Image](https://user-images.githubusercontent.com/103855697/200830136-7bd4a2e4-23ce-4b04-ba10-807bce73d857.png)


Se relleno la información de titulo, image, minidescripcion y subtitulo, para descripcion y descripcion2 se utilizo el texto de relleno Lorem. 

Espero la revisión para continuar con mi próxima tarea.

**Comment by AnderMendoza** [comment]
Esta perfecto 👍, @yeshua-aguilar qué opinas tu?
