### ISSUE TITLE
Despliegue para produccion y vista previa

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#17]
Se tiene que implementar un despliegue para el lado de producción y el lado de vistas previas, similar al [repositorio antiguo](https://github.com/AnderMendoza/Ecommerce-Template)

Se tendrán que cumplir los siguientes pasos:

- [x] Elegir un servicio de despliegue
- [x] Realizar el despliegue
- [x] Probar funcionamiento
- [x] Despliegue en un entorno cloud

**Comment by Jankarurosu** [comment]
Se encontraron unos videos que se pueden utilizar para el despliegue de la aplicación uno es en Tomcat y otro es en Azure, se revisaran los videos para ver cual es la mejor opción.

Tomcat:

https://www.youtube.com/watch?v=9xV9ZdgTDm4&ab_channel=LuigiCode 

Azure:

https://www.youtube.com/watch?v=4na62b-UVws&ab_channel=JoseAntonio  

Luego de revisar los videos, el Tomcat solamente deja desplegarlo de manera local y el Azure el plan gratuito solo deja 60 min al día.

**Comment by Jankarurosu** [comment]
Se eligió Tomcat para realizar el servicio de despliegue de la aplicación web.

**Comment by Jankarurosu** [comment]
Se realizo un pull draft para la revisión del código en este [enlace](https://github.com/Devs-Com/Stose/pull/82)
