### ISSUE TITLE
Crear CRUD para la vista Blog - frontend & backend

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#20]
Se utilizará MongoDB como base de datos para esta vista y como lenguaje Java, los datos que se tendrán que importar son:
- titulo
- imagen
- descripción

**Comment by yeshua-aguilar** [comment]
creacion de base de datos mongo



![Image](https://user-images.githubusercontent.com/81573986/200193704-b1f2372a-83e0-42bf-9020-afc5a8df3a65.png)

**Comment by yeshua-aguilar** [comment]
conexion con la base de datos a spring



![Image](https://user-images.githubusercontent.com/81573986/200193746-e66adb45-4633-481b-ae5f-427d209bb4e4.png)

**Comment by yeshua-aguilar** [comment]
creacion de modelo MVC



![Image](https://user-images.githubusercontent.com/81573986/200193755-27f39683-a6c2-4920-ab00-13f7e93e214e.png)

**Comment by yeshua-aguilar** [comment]
creacion del crud



![Image](https://user-images.githubusercontent.com/81573986/200199527-7ba35db0-4369-4638-b201-67c7c9af9ed8.png)

**Comment by yeshua-aguilar** [comment]
NOTA IMPORTANTE: TUVE QUE CAMBIAR LA VERSION DE SPRING 3.0.0 A LA 2.3.0 PORQUE ME DABA ERRORES CON EL CRUD

**Comment by AnderMendoza** [comment]
Se evidencia un gran avance, felicidades @yeshua-aguilar 😉
Ahora ya se pueden empezar a aplicar pruebas a este apartado.
