### ISSUE TITLE
Adaptar los archivos estáticos al modelo MVC

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#27]
Revisar cada archivo html, css y js de la carpeta static para agregar sus respectivos models y controllers.

**Comment by AnderMendoza** [comment]
### YA PUEDEN EMPEZAR A TRABAJAR EN LA RAMA>>> [dev](https://github.com/Devs-Com/Stose/tree/dev)

**Comment by Jankarurosu** [comment]
Ya complete mi parte correspondiente a esta tarea.

**Comment by Christofer66** [comment]
Ya complete mi parte correspondiente a esta tarea.
