### ISSUE TITLE
error de en el pie de la web con los botones de redes sociales

### ISSUE THREAD

**Issue by yeshua-aguilar** [Devs-Com/Stose#29]
**Describa el error**
en la parte del pie de la pagina existe botones a las redes sociales de la pagina web pero al hacer click en ellas no funciona

**Navegador**
estoy usando el navegador librewolf

**Capturas de pantalla**
![imagen](https://user-images.githubusercontent.com/81573986/201348903-4e80a2bc-29b0-4884-93ed-155fe28fdab7.png)

**Contexto adicional**

**Comment by yeshua-aguilar** [comment]
para la solucion seria crear redes sociales para que funciones los botones

**Comment by pedropablosalas** [comment]
**Ya esta solucionado el error**
El error ocurrio en una parte del codigo de `index` y que al no tener un buen conocimiento de **github** no se guardaron bien los cambios subiendo literal nada pero ya esta resuelto el error y ahora debera mandarte a las redes sociales al presionar los botones, los cambios fueron aplicados desde la linea **1182** hasta la **1185**

![2022-11-13 (2)](https://user-images.githubusercontent.com/108108397/201526805-ac07fd48-8538-4e01-8a90-b41d16f8d1b0.png)

avisame si es que llegas a tener algun problema para resolverlo :)

**Comment by pedropablosalas** [comment]
### IMPORTACION AL NUEVO REPOSITORIO 

Agregue el codigo que manda a las redes sociales al nuevo repositorio en cada una de las vistas, quite **Linkedin** de forma momentanea porque no sabia como crear una cuenta ahi. 

Se puede ver lo agregado [Aqui](https://github.com/Devs-Com/Stose/commit/a310e2b90352d74a9abf71dc9942df16d9c0a040)

![Image](https://user-images.githubusercontent.com/108108397/201532562-ede2edb6-9d24-4474-b992-7566fb399dcb.png)
