### ISSUE TITLE
Descripción e imágenes de todos los libros

### ISSUE THREAD

**Issue by 74585289** [Devs-Com/Stose#35]
**Describe the bug**
Solo hay descripción de un par de libros, y no de todos

**Browser**
Chrome, Firefox, etc.

**Screenshots**

**Additional context**

**Comment by 74585289** [comment]
Se irá rellenando la base de datos con la descripción de casa libro

**Comment by Jankarurosu** [comment]
Se completo de llenar la base de datos id_138 hasta id_294 con su link de la imagen y la descripción

**Comment by DiegoCuadros** [comment]
Llenado de id_41 hasta id_137,  puesto link de imagen y descripcion de cada uno

**Comment by AnderMendoza** [comment]
Se ha reflejado el aporte de cada uno de los asignados. Gran trabajo @DiegoCuadros @74585289 @Jankarurosu 👌
