### ISSUE TITLE
Crear redes sociales - frontend

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#46]
Crear las redes sociales que se muestran en el footer de la página web.

![Image](https://user-images.githubusercontent.com/80181518/201155903-71c86ee6-c20b-42d8-9da6-7b35def4d3f1.png)

**Comment by pedropablosalas** [comment]
**Redes sociales agregadas**

Agregue las redes sociales a cada una de las vistas de la pagina y quite de forma momentanea el boton de **Linkedin** debido que no sabia como crear una cuenta ahi.


![Image](https://user-images.githubusercontent.com/108108397/201532562-ede2edb6-9d24-4474-b992-7566fb399dcb.png)

**Comment by AnderMendoza** [comment]
Se integro de manera correcta en cada una de las vistas, gran aporte @pedropablosalas 😉👌
