### ISSUE TITLE
Editar el header con los últimos cambios

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#59]
## Colocar los espacios marcados en todas las demás vistas

![Image](https://user-images.githubusercontent.com/80181518/202319202-f6c067a1-7e01-4db5-addb-1563dcca3b80.png)

**Comment by Jankarurosu** [comment]
Se realizo el commit con la tarea designada se puede revisar [acá](https://github.com/Devs-Com/Stose/commit/53b1548258d99a519938d139f9d6ef3bc4135c0e)

**Comment by AnderMendoza** [comment]
Falta cambiar la vista de costos de envió


![Image](https://user-images.githubusercontent.com/80181518/203874685-16d66533-ce1d-4ae3-ba18-7491d82a4e90.png)

**Comment by AnderMendoza** [comment]
Se ha corregido en el PR #61, con lo relacionado a esta tarea se evidencia una correcta edición del campo solicitado. Gran aporte @Jankarurosu 👌
