### ISSUE TITLE
Bug en la vista de costo de envio

### ISSUE THREAD

**Issue by yeshua-aguilar** [Devs-Com/Stose#60]
**Describa el error**
Hay un error en la vista de costo de envío que no funcionas los botones

**Navegador**
¿Qué navegador estás usando? Ejemplos: Chrome, Firefox, etc.

**Capturas de pantalla**
![imagen](https://user-images.githubusercontent.com/81573986/202586521-967f7097-2234-42c7-a147-a5de35af3289.png)

**Contexto adicional**
No funciona la barra de categoría, los botones de abajo del pie dela web

**Comment by AnderMendoza** [comment]
Se ha resuelto la tarea en el PR #61
