### ISSUE TITLE
Editar la tabla del CRUD

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#65]
- [x] Se tiene que poder mostrar las imágenes que se han insertado en la bd de MySQL en la vista del CRUD creado.
- [x] Ajustar la resolución de las imágenes mostradas en la tabla
- [x] Agregar un campo más para insertar la url de la imagen en la vista de agregar libro
- [x] Agregar un campo más para insertar la url de la imagen en la vista de editar libro

**Comment by Jankarurosu** [comment]
Llama correctamente a las imágenes en el CRUD, sin embargo el tamaño de estas no esta especificado, por lo que desordena la tabla mostrada.



![Image](https://user-images.githubusercontent.com/103855697/203875732-f38161c4-3195-4ff7-9444-2f82c38d7de0.png)

**Comment by Jankarurosu** [comment]
Se ajusto la resolución de las imágenes en el CRUD, se puso de tamaño `width="100"` y `height="100"` porque si se agrega mas tamaño la tabla se sale de los limites.



![Image](https://user-images.githubusercontent.com/103855697/204143113-409a677b-9949-4a10-b169-c7193bbeba7a.png)

**Comment by Jankarurosu** [comment]
Se agrego un campo arriba de "Titulo" para poder añadir y editar el libro en los campos de "Agregar libro" y "Editar"



![Image](https://user-images.githubusercontent.com/103855697/204143392-b45707de-33bd-430c-8d3a-54c427ece997.png)



![Image](https://user-images.githubusercontent.com/103855697/204143360-efed3b90-9328-4840-8889-beb2e0c36a86.png)

**Comment by Jankarurosu** [comment]
Se realizo un pull draft de esta tarea [aquí ](https://github.com/Devs-Com/Stose/pull/72)

**Comment by AnderMendoza** [comment]
Se confirmo el PR luego de la revision del codigo.
Buen trabajo 👌
