### ISSUE TITLE
Imágenes en el slider del inicio

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#66]
Se tienen que agregar 4 imágenes como parte del slider mostrada en la vista de inicio.
Esta inserción debe ser solo por HTML.

**Comment by DiegoCuadros** [comment]
He terminado la tarea que me dejaste [Tarea](https://github.com/Devs-Com/Stose/pull/69)

**Comment by DiegoCuadros** [comment]
![Image](https://user-images.githubusercontent.com/81636439/204018415-369cef97-e52f-4af1-9aee-500146773a48.png)

**Comment by AnderMendoza** [comment]
Se ha revisado el resultado en la vista, se evidencia una correcta inserción de las imágenes, Gran trabajo @DiegoCuadros 👍
