### ISSUE TITLE
Llenar datos en la base de datos MySQL

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#75]
Se han agregado más campos a rellenar en la bd, los campos son los siguientes:

![Image](https://user-images.githubusercontent.com/80181518/204966470-e711aaff-9301-43cf-99b5-b88aede2390e.png)

**Comment by Jankarurosu** [comment]
Se rellenaron los campos nuevos de `precio_descuento` y `porcentaje_descuento` desde el `id_1` hasta el `id_294` en la base de datos, se usaron descuentos de 10%, 15% y 20%.

Imagen: 

![Image](https://user-images.githubusercontent.com/103855697/205159648-4b20f699-28e5-42ce-8e3b-cc0cf82fa922.png)


Se agrego en el `id_294` un descuento del 70%, para la oferta.


![Image](https://user-images.githubusercontent.com/103855697/205160453-8ff1e06c-8bd9-4fd0-8dc6-891c340f5952.png)

**Comment by AnderMendoza** [comment]
Se ha revisado la inserción de los datos en la bd. Todo correcto.
