### ISSUE TITLE
Error en la vista index.html en Oferta

### ISSUE THREAD

**Issue by yeshua-aguilar** [Devs-Com/Stose#80]
**Describe** the bug
Un error en la parte de oferta.

**Screenshots**
![image](https://user-images.githubusercontent.com/81573986/206346116-e07ada4c-6711-44e6-aa71-29d6eecb8a66.png)

**Additional**
El error es sobre el diseño como se ve marcado que sobre sale hacia abajo, he intentado arreglar pero no entiendo. como es que crearon ese cuadro negro alrededor si pudieran modificar el código de ese cuadro para que se vea mejor.

**Comment by AnderMendoza** [comment]
Se recomienda mostrar solo 2 columnas de 4 filas de libros mostrados al lado del libro en oferta para corregir dicho espacio.
Quedo atento al resultado @yeshua-aguilar 😉
