### ISSUE TITLE
Crear vista de Lista de Deseos - frontend

### ISSUE THREAD

**Issue by AnderMendoza** [Devs-Com/Stose#9]
- Reutilizando el código del carrito de compras desplegable integrarlo al icon de lista de deseos del header-nav, quitando algunos valores como el boton de verificar, precio total y cambiar el boton de ver carrito a ver lista de deseos
Mostrar algo similar a esto, pero para el otro icon:

![Image](https://user-images.githubusercontent.com/80181518/199143036-9c65f0c5-636f-48c9-8eda-39a3206c2edd.png)

- Para la creación de la vista se puede también reutilizar el código de la vista de carrito-compras, quitando algunos valores de la tabla que no son tan necesarios de mostrar

**Comment by Jankarurosu** [comment]
Estoy terminando la parte de la lista de deseos:


![Image](https://user-images.githubusercontent.com/103855697/200087215-b9136ab6-5454-43cb-82e6-20593e9444c1.png)


Aun me falta insertarlo en las demás vistas, estoy trabajando en un fork del repositorio antiguo acá dejo el enlace:

https://github.com/Jankarurosu/Ecommerce-Template

**Comment by Jankarurosu** [comment]
Se realizo un pull draft presentando el avance de la tarea, estoy a la espera de la revisión. 

Enlace: 

https://github.com/AnderMendoza/Ecommerce-Template/pull/112

**Comment by Jankarurosu** [comment]
Se actualizo la vista de lista de deseos agregando mas valores a la tabla:



![Image](https://user-images.githubusercontent.com/103855697/200574726-e07e4615-1f0f-4f66-863f-4f6a1b7ed751.png)


Dejo el enlace del pull draft:

https://github.com/AnderMendoza/Ecommerce-Template/pull/112

Espero la revisión.

**Comment by AnderMendoza** [comment]
Ya te dejé un comentario revísalo [aquí](https://github.com/AnderMendoza/Ecommerce-Template/pull/112#issuecomment-1307228989), espero tu respuesta.

**Comment by Jankarurosu** [comment]
Se actualizo la tabla en base a la revisión: 

![Image](https://user-images.githubusercontent.com/103855697/200584430-88ecf8f7-6578-4fe3-9f0e-e648bc5592d8.png)

Dejo el enlace del pull draft:

https://github.com/AnderMendoza/Ecommerce-Template/pull/112

**Comment by AnderMendoza** [comment]
Ya te dejé un comentario revísalo [aquí](https://github.com/AnderMendoza/Ecommerce-Template/pull/112#issuecomment-1307311209), espero tu respuesta.

**Comment by AnderMendoza** [comment]
En el [commit](https://github.com/AnderMendoza/Ecommerce-Template/pull/112/commits/89e5a3f6819d5bf778a1626ef277028790fbd546) que realice resolví el problema existente, ahora solo faltaría que se adapte a las demás vistas.

**Comment by Jankarurosu** [comment]
@AnderMendoza Se implemento la lista de deseos con el responsive a todas las vistas.

Dejo el enlace del pull draft:

https://github.com/AnderMendoza/Ecommerce-Template/pull/112

**Comment by AnderMendoza** [comment]
Revisar el comentario que se ha colocado en la PR.

**Comment by Jankarurosu** [comment]
Se corrigió el error:



![Image](https://user-images.githubusercontent.com/103855697/201114248-fe20849f-ae56-4a51-afde-f5b6692b07c8.png)


Dejo el enlace del pull draft:

https://github.com/AnderMendoza/Ecommerce-Template/pull/112

**Comment by AnderMendoza** [comment]
Se realizo el [merged](https://github.com/AnderMendoza/Ecommerce-Template/pull/112) en la PR realizada en el [repositorio anterior](https://github.com/AnderMendoza/Ecommerce-Template).
Buen trabajo 😉

**Comment by AnderMendoza** [comment]
Falta la inserción de este apartado en cada una de las vistas en el modelo MVC

**Comment by Jankarurosu** [comment]
Se termino la inserción de la Lista de Deseos con el modelo MVC solicitado, se puede revisar en [este commit](https://github.com/Devs-Com/Stose/commit/0a4c01a1bd7731928bf98cfc2861d8e79530cd79)

**Comment by AnderMendoza** [comment]
En el header-nav el logo no redirigue al inicio

![Captura de pantalla 2022-11-16 180624](https://user-images.githubusercontent.com/80181518/202314139-a39817a2-8020-40b6-80b8-eaa10d4582c6.png)

![Captura de pantalla 2022-11-16 180616](https://user-images.githubusercontent.com/80181518/202314164-b3c6b843-c9e8-4ac7-8c4f-9a35c7d9414f.png)

**Comment by Jankarurosu** [comment]
Se arreglo el error, se puede revisar en [este commit](https://github.com/Devs-Com/Stose/commit/b535a90ab12a5436ea0c7097e5285f9c606712b6)

**Comment by AnderMendoza** [comment]
Se implemento los espacios según lo requerido, buen trabajo 😉
